fragment issueCards on ProjectColumn {
    cards(first: 100) {
        nodes {
            column { name }
            content {
                ... on Issue {
                    number
                    title
                    milestone { title }
                }
            }
        }
    }
} 

query  {
    nodes(ids: ["MDEzOlByb2plY3RDb2x1bW4xMzAyMTI1NA==", "PC_lQHOAI6QIs4PIgPjzgCz4YHOAOFeiA"]) {
        ...issueCards
    }
}